***** Used to labele HCCs 
cap label drop cc_label
cap label drop short_ccs

#delimit ; 
label define cc_label
    1     "HIV/AIDS"
    2     "Septicemia, Sepsis, Systemic Inflammatory Response Syndrome/Shock"
    3     "Central Nervous System Infections, Except Viral Meningitis"
    4     "Viral or Unspecified Meningitis"
    6     "Opportunistic Infections"
    8     "Metastatic Cancer"
    9     "Lung, Brain, and Other Severe Cancers, Including Pediatric Acute Lymphoid Leukemia"
    10     "Non-Hodgkin's Lymphomas and Other Cancers and Tumors"
    11     "Colorectal, Breast (Age < 50), Kidney, and Other Cancers"
    12     "Breast (Age 50+) and Prostate Cancer, Benign/Uncertain Brain Tumors, and Other Cancers and Tumors"
    13     "Thyroid Cancer, Melanoma, Neurofibromatosis, and Other Cancers and Tumors"
    18     "Pancreas Transplant Status/Complications"
    19     "Diabetes with Acute Complications"
    20     "Diabetes with Chronic Complications"
    21     "Diabetes without Complication"
    23     "Protein-Calorie Malnutrition"
    26     "Mucopolysaccharidosis"
    27     "Lipidoses and Glycogenosis"
    28     "Congenital Metabolic Disorders, Not Elsewhere Classified"
    29     "Amyloidosis, Porphyria, and Other Metabolic Disorders"
    30     "Adrenal, Pituitary, and Other Significant Endocrine Disorders"
    34     "Liver Transplant Status/Complications"
    35     "End-Stage Liver Disease"
    36     "Cirrhosis of Liver"
    37     "Chronic Hepatitis"
    38     "Acute Liver Failure/Disease, Including Neonatal Hepatitis"
    41     "Intestine Transplant Status/Complications"
    42     "Peritonitis/Gastrointestinal Perforation/Necrotizing Enterocolitis"
    45     "Intestinal Obstruction"
    46     "Chronic Pancreatitis"
    47     "Acute Pancreatitis/Other Pancreatic Disorders and Intestinal Malabsorption"
    48     "Inflammatory Bowel Disease"
    54     "Necrotizing Fasciitis"
    55     "Bone/Joint/Muscle Infections/Necrosis"
    56     "Rheumatoid Arthritis and Specified Autoimmune Disorders"
    57     "Systemic Lupus Erythematosus and Other Autoimmune Disorders"
    61     "Osteogenesis Imperfecta and Other Osteodystrophies"
    62     "Congenital/Developmental Skeletal and Connective Tissue Disorders"
    63     "Cleft Lip/Cleft Palate"
    64     "Major Congenital Anomalies of Diaphragm, Abdominal Wall, and Esophagus, Age < 2"
    66     "Hemophilia"
    67     "Myelodysplastic Syndromes and Myelofibrosis"
    68     "Aplastic Anemia"
    69     "Acquired Hemolytic Anemia, Including Hemolytic Disease of Newborn"
    70     "Sickle Cell Anemia (Hb-SS)"
    71     "Thalassemia Major"
    73     "Combined and Other Severe Immunodeficiencies"
    74     "Disorders of the Immune Mechanism"
    75     "Coagulation Defects and Other Specified Hematological Disorders"
    81     "Drug Psychosis"
    82     "Drug Dependence"
    87     "Schizophrenia"
    88     "Major Depressive and Bipolar Disorders"
    89     "Reactive and Unspecified Psychosis, Delusional Disorders"
    90     "Personality Disorders"
    94     "Anorexia/Bulimia Nervosa"
    96     "Prader-Willi, Patau, Edwards, and Autosomal Deletion Syndromes"
    97     "Down Syndrome, Fragile X, Other Chromosomal Anomalies, and Congenital Malformation Syndromes"
    102     "Autistic Disorder"
    103     "Pervasive Developmental Disorders, Except Autistic Disorder"
    106     "Traumatic Complete Lesion Cervical Spinal Cord"
    107     "Quadriplegia"
    108     "Traumatic Complete Lesion Dorsal Spinal Cord"
    109     "Paraplegia"
    110     "Spinal Cord Disorders/Injuries"
    111     "Amyotrophic Lateral Sclerosis and Other Anterior Horn Cell Disease"
    112     "Quadriplegic Cerebral Palsy"
    113     "Cerebral Palsy, Except Quadriplegic"
    114     "Spina Bifida and Other Brain/Spinal/Nervous System Congenital Anomalies"
    115     "Myasthenia Gravis/Myoneural Disorders and Guillain-Barre Syndrome/Inflammatory and Toxic Neuropathy"
    117     "Muscular Dystrophy"
    118     "Multiple Sclerosis"
    119     "Parkinson's, Huntington's, and Spinocerebellar Disease, and Other Neurodegenerative Disorders"
    120     "Seizure Disorders and Convulsions"
    121     "Hydrocephalus"
    122     "Non-Traumatic Coma, Brain Compression/Anoxic Damage"
    125     "Respirator Dependence/Tracheostomy Status"
    126     "Respiratory Arrest"
    127     "Cardio-Respiratory Failure and Shock, Including Respiratory Distress Syndromes"
    128     "Heart Assistive Device/Artificial Heart"
    129     "Heart Transplant"
    130     "Congestive Heart Failure"
    131     "Acute Myocardial Infarction"
    132     "Unstable Angina and Other Acute Ischemic Heart Disease"
    135     "Heart Infection/Inflammation, Except Rheumatic"
    137     "Hypoplastic Left Heart Syndrome and Other Severe Congenital Heart Disorders"
    138     "Major Congenital Heart/Circulatory Disorders"
    139     "Atrial and Ventricular Septal Defects, Patent Ductus Arteriosus, and Other Congenital Heart/Circulatory Disorders"
    142     "Specified Heart Arrhythmias"
    145     "Intracranial Hemorrhage"
    146     "Ischemic or Unspecified Stroke"
    149     "Cerebral Aneurysm and Arteriovenous Malformation"
    150     "Hemiplegia/Hemiparesis"
    151     "Monoplegia, Other Paralytic Syndromes"
    153     "Atherosclerosis of the Extremities with Ulceration or Gangrene"
    154     "Vascular Disease with Complications"
    156     "Pulmonary Embolism and Deep Vein Thrombosis"
    158     "Lung Transplant Status/Complications"
    159     "Cystic Fibrosis"
    160     "Chronic Obstructive Pulmonary Disease, Including Bronchiectasis"
    161     "Asthma"
    162     "Fibrosis of Lung and Other Lung Disorders"
    163     "Aspiration and Specified Bacterial Pneumonias and Other Severe Lung Infections"
    183     "Kidney Transplant Status"
    184     "End Stage Renal Disease"
    187     "Chronic Kidney Disease, Stage 5"
    188     "Chronic Kidney Disease, Severe (Stage 4)"
    203     "Ectopic and Molar Pregnancy, Except with Renal Failure, Shock, or Embolism"
    204     "Miscarriage with Complications"
    205     "Miscarriage with No or Minor Complications"
    207     "Completed Pregnancy With Major Complications"
    208     "Completed Pregnancy With Complications"
    209     "Completed Pregnancy with No or Minor Complications"
    217     "Chronic Ulcer of Skin, Except Pressure"
    226     "Hip Fractures and Pathological Vertebral or Humerus Fractures"
    227     "Pathological Fractures, Except of Vertebrae, Hip, or Humerus"
    242     "Extremely Immature Newborns, Birthweight < 500 Grams"
    243     "Extremely Immature Newborns, Including Birthweight 500-749 Grams"
    244     "Extremely Immature Newborns, Including Birthweight 750-999 Grams"
    245     "Premature Newborns, Including Birthweight 1000-1499 Grams"
    246     "Premature Newborns, Including Birthweight 1500-1999 Grams"
    247     "Premature Newborns, Including Birthweight 2000-2499 Grams"
    248     "Other Premature, Low Birthweight, Malnourished, or Multiple Birth Newborns"
    249     "Term or Post-Term Singleton Newborn, Normal or High Birthweight"
    251     "Stem Cell, Including Bone Marrow, Transplant Status/Complications"
    253     "Artificial Openings for Feeding or Elimination"
    254     "Amputation Status, Lower Limb/Amputation Complications"
; 

label define short_ccs
    1     "HIV/AIDS"
    2     "Sepsis & Shock"
    3     "Brain Infections"
    4     "Viral Meningitis"
    6     "Opportunistic Infections"
    8     "Metastatic Cancer"
    9     "Lung/Brain Cancers"
    10     "Non-Hodgkin's Lymphomas"
    11     "Early Breast/Kidney/Colorectal Cancer"
    12     "50+ Breast and Prostate Cancer"
    13     "Thyroid Cancer"
    18     "Pancreas Transplant"
    19     "Diab. w/ Acute Comp."
    20     "Diabetes w/ Comp."
    21     "Diabetes w/o Comp."
    23     "Malnutrition"
    26     "Mucopolysaccharidosis"
    27     "Lipidoses"
    28     "Metabolic Disorders"
    29     "Amyloidosis, Porphyria"
    30     "Adrenal/Pituitary Dis."
    34     "Liver Transplant"
    35     "End-Stage Liver Disease"
    36     "Cirrhosis of Liver"
    37     "Chronic Hepatitis"
    38     "Acute Liver Failure"
    41     "Intestine Transplant"
    42     "Ruptured Bowel"
    45     "Intestinal Obstruction"
    46     "Chronic Pancreatitis"
    47     "Acute Pancreatitis"
    48     "Inflammatory Bowel Disease"
    54     "Necrotizing Fasciitis"
    55     "Bone/Joint/Muscle Infection"
    56     "Rheumatoid Arthritis"
    57     "Lupus"
    61     "Osteogenesis Imperfecta"
    62     "Congenital Skeletal Disorder"
    63     "Cleft Lip/Cleft Palate"
    64     "Congenital Anomalies, Age < 2"
    66     "Hemophilia"
    67     "Myelodysplasma"
    68     "Aplastic Anemia"
    69     "Acquired Hemolytic Anemia"
    70     "Sickle Cell Anemia (Hb-SS)"
    71     "Thalassemia Major"
    73     "Severe Immunodeficiencies"
    74     "Immune Disorders"
    75     "Coagulation Defects"
    81     "Drug Psychosis"
    82     "Drug Dependence"
    87     "Schizophrenia"
    88     "MDD and Bipolar"
    89     "Psychosis"
    90     "Personality Disorder"
    94     "Eating Disorder"
    96     "Autosomal Deletion Syndromes"
    97     "Down Syndrome"
    102     "Autism"
    103     "Developmental Disorder"
    106     "Cervical Spine Injury"
    107     "Quadriplegia"
    108     "Dorsal Spine Injury"
    109     "Paraplegia"
    110     "Spinal Cord Disorders/Injuries"
    111     "ALS"
    112     "Quadriplegic CP"
    113     "Other CP"
    114     "Spina Bifida"
    115     "Myasthenia Gravis"
    117     "Muscular Dystrophy"
    118     "Multiple Sclerosis"
    119     "Neurodegenerative Dis."
    120     "Seizures"
    121     "Hydrocephalus"
    122     "Coma"
    125     "Respirator Dependence"
    126     "Respiratory Arrest"
    127     "Cardio-Respiratory Failure"
    128     "Heart Device"
    129     "Heart Transplant"
    130     "Congestive Heart Failure"
    131     "AMI (Heart Attack)"
    132     "Unstable Angina"
    135     "Heart Infection"
    137     "Severe Congenital Heart Dis."
    138     "Major Congenital Heart Dis."
    139     "Septal Defects"
    142     "Heart Arrhythmias"
    145     "Intracranial Hemorrhage"
    146     "Stroke"
    149     "Cerebral Aneurysm"
    150     "Hemiplegia/Hemiparesis"
    151     "Paralytic Syndromes"
    153     "Atherosclerosis"
    154     "Vascular Disease"
    156     "Pulmonary Embolism"
    158     "Lung Transplant"
    159     "Cystic Fibrosis"
    160     "COPD"
    161     "Asthma"
    162     "Fibrosis of Lung"
    163     "Severe Lung Infections"
    183     "Kidney Transplant Status"
    184     "ESRD"
    187     "Kidney Disease (s5)"
    188     "Kidney Disease (s4)"
    203     "Ectopic Pregnancy"
    204     "Miscarriage w/ Comp."
    205     "Miscarriage w/o Comp."
    207     "Pregnancy w/ Major Comp."
    208     "Pregnancy w/ Comp."
    209     "Pregnancy w/o Comp."
    217     "Chronic Skin Ulcer"
    226     "Hip Fractures"
    227     "Pathological Fractures"
    242     "Immature Newborn: < 500g"
    243     "Immature Newborn: 500-749g"
    244     "Immature Newborn: 750-999g"
    245     "Premature Newborn: 1000-1499g"
    246     "Premature Newborn: 1500-1999g"
    247     "Premature Newborn: 2000-2499g"
    248     "Low Weight/Multiple Birth Newborns"
    249     "Singleton Newborn"
    251     "Stem Cell Transplant"
    253     "Artificial Openings"
    254     "Lower Limb/Amputation"
; 
#delimit cr
